{% set name = "gs-quant" %}
{% set version = "1.4.26" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gs_quant-{{ version }}.tar.gz
  sha256: 637fc13b2139025a4a96eb4d7ad34865479652b7e2c54db5e3ffe6657d14c67d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - aenum
    - backoff
    - cachetools
    - certifi
    - dataclasses-json
    - deprecation
    - inflection
    - lmfit
    - more-itertools
    - msgpack-python
    - nest-asyncio
    - numpy >1.17.0
    - opentelemetry-api
    - opentelemetry-sdk
    - pandas >=1.4
    - pydash <7.0.0
    - python-dateutil >=2.7.0
    - requests
    - httpx >=0.23.3
    - scipy >=1.2.0
    - statsmodels >=0.13.0
    - tqdm
    - websockets

test:
  imports:
    - gs_quant
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://marquee.gs.com
  summary: Goldman Sachs Quant
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - apmorton
