{% set name = "gs-quant" %}
{% set version = "1.0.99" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gs_quant-{{ version }}.tar.gz
  sha256: 2e12a5c460b475e59c4249fd82daa3ae85609ad5c2c1fe7c25275783c624b6de

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - aenum
    - backoff
    - cachetools
    - certifi
    - dataclasses-json
    - deprecation
    - funcsigs
    - httpx >=0.23.3
    - inflection
    - lmfit
    - more-itertools
    - msgpack-python
    - nest-asyncio
    - numpy <2.0.0
    - opentracing
    - pandas >=1.4,<2.2
    - pydash <7.0.0
    - python-dateutil >=2.7.0
    - requests
    - scipy >=1.2.0
    - statsmodels >=0.13.0
    - tqdm
    - websockets

test:
  imports:
    - gs_quant
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://marquee.gs.com
  summary: Goldman Sachs Quant
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - apmorton
