{% set name = "gs-quant" %}
{% set version = "1.3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gs_quant-{{ version }}.tar.gz
  sha256: d547812f4dfe48cb1a71eabf4ce300e272f6b7e261873c26575133dd3e9801d2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - aenum
    - backoff
    - cachetools
    - certifi
    - dataclasses-json
    - deprecation
    - freezegun
    - funcsigs
    - httpx >=0.23.3
    - inflection
    - lmfit
    - more-itertools
    - msgpack-python
    - nest-asyncio
    - numpy <2.0.0
    - opentracing
    - pandas >=1.4
    - pydash <7.0.0
    - python-dateutil >=2.7.0
    - pytz ==2024.1
    - requests
    - scipy >=1.2.0
    - statsmodels >=0.13.0
    - tqdm
    - websockets

test:
  imports:
    - gs_quant
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://marquee.gs.com
  summary: Goldman Sachs Quant
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - apmorton
